name: Daily ZenML Pipeline Run

on:
  workflow_dispatch:      # Manual trigger from GitHub UI
  schedule:
    - cron: "0 8 * * *"    # Runs every day at 8 AM UTC

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
       QDRANT_URL: ${{ secrets.QDRANT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: print QDRANT url
        run: |
          echo $QDRANT_URL

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          source venv/bin/activate
          python run_pipeline.py
